/**
 * js/shapes/catenoid.js
 * 構造の説明: カテノイド（懸垂面）
 */

import { parametric } from "../utils.js";

export const catenoid = {
  title: "Catenoid",
  hideVertices: true,
  desc: [
    "A catenoid is the only minimal surface of revolution except for the plane. It is generated by rotating a catenary (the shape of a hanging chain) around an axis.",
    "It was discovered by Leonhard Euler in 1744. It can be physically modeled as a soap film stretched between two circular rings. Topologically equivalent to an annulus, it has zero mean curvature at every point.",
  ],
  formulas: [
    {
      label: "Equation (Surface of Revolution)",
      eq: "\\sqrt{x^2 + y^2} = c \\cosh(\\frac{z}{c})",
    },
    { label: "Mean Curvature", eq: "H = 0" },
    {
      label: "Gaussian Curvature",
      eq: "-\\text{sech}^4(\\frac{z}{c})/c^2",
    },
  ],
  /**
   * カテノイドの頂点と面を生成します。
   * @returns {Object} {vertices, faces}
   */
  generate: () =>
    parametric(
      40,
      40,
      (u, v) => {
        const c = 0.5;
        const x = c * Math.cosh(v / c) * Math.cos(u);
        const y = c * Math.cosh(v / c) * Math.sin(u);
        const z = v;
        const s = 0.55;
        return { x: x * s, y: y * s, z: z * s };
      },
      [0, Math.PI * 2],
      [-1.2, 1.2],
    ),
};
