/**
 * js/shapes/index.js
 * 階層的なカテゴリ分けを持つ、すべての幾何学的形状の中央レジストリ。
 */

import { tetrahedron } from "./tetrahedron.js";
import { cube } from "./cube.js";
import { octahedron } from "./octahedron.js";
import { dodecahedron } from "./dodecahedron.js";
import { icosahedron } from "./icosahedron.js";
import { bucky } from "./bucky.js";
import { sphere } from "./sphere.js";
import { torus } from "./torus.js";
import { mobius } from "./mobius.js";
import { klein } from "./klein.js";
import { boy } from "./boy.js";
import { hyper } from "./hyper.js";
import { dini } from "./dini.js";
import { enneper } from "./enneper.js";
import { roman } from "./roman.js";
import { kuen } from "./kuen.js";
import { catenoid } from "./catenoid.js";
import { dna } from "./dna.js";
import { knot } from "./knot.js";
import { superShape } from "./super.js";
import { calabi } from "./calabi.js";
import { lorenz } from "./lorenz.js";
import { tesseract } from "./tesseract.js";
import { orrery } from "./orrery.js";

// 新しく追加された形状
import { sierpinski } from "./sierpinski.js";
import { honeycomb } from "./honeycomb.js";
import { chladni } from "./chladni.js";
import { interference } from "./interference.js";
import { schwarzschild } from "./schwarzschild.js";
import { diamond } from "./diamond.js";
import { nanotube } from "./nanotube.js";
import { radiolarian } from "./radiolarian.js";
import { capsid } from "./capsid.js";

import { breather } from "./breather.js";
import { graphite } from "./graphite.js";
import { phyllotaxis } from "./phyllotaxis.js";
import { diatom } from "./diatom.js";
import { binaryTree } from "./tree.js";

// ギャラリー用の階層的なカテゴリを定義
export const disciplines = [
  {
    name: "Mathematics",
    theme: "math",
    desc: "The study of numbers, shapes, and patterns that form the foundation of logic.",
    groups: [
      {
        name: "Platonic Solids",
        desc: "Regular, convex polyhedra with identical faces made of regular polygons.",
        shapes: [
          "tetrahedron",
          "cube",
          "octahedron",
          "dodecahedron",
          "icosahedron",
        ],
      },
      {
        name: "Geometric Surfaces",
        desc: "Fundamental shapes and smooth surfaces found in classical geometry.",
        shapes: [
          "sphere",
          "torus",
          "hyper",
          "catenoid",
          "enneper",
          "dini",
          "kuen",
          "breather",
        ],
      },
      {
        name: "Fractals and Tilings",
        desc: "Complex patterns generated by simple recursive rules or efficient space-filling.",
        shapes: ["sierpinski", "honeycomb"],
      },
      {
        name: "Topology and Higher Dimensions",
        desc: "Shapes that explore connectivity and dimensions beyond our everyday experience.",
        shapes: ["mobius", "klein", "boy", "roman", "knot", "tesseract"],
      },
    ],
  },
  {
    name: "Physics",
    theme: "physics",
    desc: "The science of matter, energy, and the fundamental forces of the universe.",
    groups: [
      {
        name: "Waves and Vibrations",
        desc: "Visualizations of wave interference and resonant frequencies.",
        shapes: ["chladni", "interference"],
      },
      {
        name: "Celestial Mechanics and Astrophysics",
        desc: "The study of orbital motions and the nature of celestial bodies.",
        shapes: ["orrery", "schwarzschild"],
      },
      {
        name: "Chaos and Dynamical Systems",
        desc: "Complex behaviors emerging from simple deterministic laws.",
        shapes: ["lorenz"],
      },
      {
        name: "Quantum Mechanics",
        desc: "Mathematical models of atomic structures and higher-dimensional manifolds.",
        shapes: ["calabi"],
      },
    ],
  },
  {
    name: "Chemistry",
    theme: "chemistry",
    desc: "The study of substances, their properties, and how they interact and change.",
    groups: [
      {
        name: "Crystal Lattices",
        desc: "Ordered arrangements of atoms and ions in solid materials.",
        shapes: ["diamond", "graphite"],
      },
      {
        name: "Molecular Nanostructures",
        desc: "The geometry of fullerenes and carbon-based nanomaterials.",
        shapes: ["bucky", "nanotube"],
      },
    ],
  },
  {
    name: "Biology",
    theme: "biology",
    desc: "The study of living organisms and the vital processes that sustain life.",
    groups: [
      {
        name: "Biological Morphogenesis",
        desc: "Geometric patterns found in plant growth and organic forms.",
        shapes: ["super", "phyllotaxis"],
      },
      {
        name: "Microscopic Structures",
        desc: "The intricate skeletons and shells of microscopic organisms and viruses.",
        shapes: ["dna", "radiolarian", "capsid", "diatom"],
      },
    ],
  },
  {
    name: "Engineering & CS",
    theme: "engineering",
    desc: "Application of science and math to solve problems and build structures.",
    groups: [
      {
        name: "Recursive Algorithms",
        desc: "Visualization of data structures and recursive state spaces.",
        shapes: ["tree"],
      },
    ],
  },
];

// Flat registry for the viewer
export const shapes = {
  tetrahedron,
  cube,
  octahedron,
  dodecahedron,
  icosahedron,
  bucky,
  sphere,
  torus,
  mobius,
  klein,
  boy,
  hyper,
  dini,
  enneper,
  roman,
  kuen,
  catenoid,
  dna,
  knot,
  super: superShape,
  calabi,
  lorenz,
  tesseract,
  orrery,
  sierpinski,
  honeycomb,
  chladni,
  interference,
  schwarzschild,
  diamond,
  nanotube,
  radiolarian,
  capsid,
  breather,
  graphite,
  phyllotaxis,
  diatom,
  tree: binaryTree,
};
