/**
 * js/shapes/surfaces.js
 * Mathematical surfaces and manifolds with enriched descriptions and formulas.
 */

import { parametric } from "../utils.js";

/**
 * Generates an Icosphere by subdividing an icosahedron.
 * Results in more uniform vertex distribution than UV-spheres.
 */
const icosphere = (iterations = 2, scale = 0.8) => {
  const phi = (1 + Math.sqrt(5)) / 2;
  let vertices = [
    { x: -1, y: phi, z: 0 },
    { x: 1, y: phi, z: 0 },
    { x: -1, y: -phi, z: 0 },
    { x: 1, y: -phi, z: 0 },
    { x: 0, y: -1, z: phi },
    { x: 0, y: 1, z: phi },
    { x: 0, y: -1, z: -phi },
    { x: 0, y: 1, z: -phi },
    { x: phi, y: 0, z: -1 },
    { x: phi, y: 0, z: 1 },
    { x: -phi, y: 0, z: -1 },
    { x: -phi, y: 0, z: 1 },
  ];
  let faces = [
    [0, 11, 5],
    [0, 5, 1],
    [0, 1, 7],
    [0, 7, 10],
    [0, 10, 11],
    [1, 5, 9],
    [5, 11, 4],
    [11, 10, 2],
    [10, 7, 6],
    [7, 1, 8],
    [3, 9, 4],
    [3, 4, 2],
    [3, 2, 6],
    [3, 6, 8],
    [3, 8, 9],
    [4, 9, 5],
    [2, 4, 11],
    [6, 2, 10],
    [8, 6, 7],
    [9, 8, 1],
  ];

  const normalize = (v) => {
    const l = Math.sqrt(v.x * v.x + v.y * v.y + v.z * v.z) || 1;
    return { x: v.x / l, y: v.y / l, z: v.z / l };
  };

  vertices = vertices.map(normalize);

  const getMidpoint = (p1Idx, p2Idx, cache) => {
    const key = p1Idx < p2Idx ? `${p1Idx}-${p2Idx}` : `${p2Idx}-${p1Idx}`;
    if (cache.has(key)) return cache.get(key);
    const p1 = vertices[p1Idx],
      p2 = vertices[p2Idx];
    const mid = normalize({
      x: (p1.x + p2.x) / 2,
      y: (p1.y + p2.y) / 2,
      z: (p1.z + p2.z) / 2,
    });
    vertices.push(mid);
    const idx = vertices.length - 1;
    cache.set(key, idx);
    return idx;
  };

  for (let i = 0; i < iterations; i++) {
    const nextFaces = [];
    const cache = new Map();
    faces.forEach(([a, b, c]) => {
      const ab = getMidpoint(a, b, cache);
      const bc = getMidpoint(b, c, cache);
      const ca = getMidpoint(c, a, cache);
      nextFaces.push([a, ab, ca], [b, bc, ab], [c, ca, bc], [ab, bc, ca]);
    });
    faces = nextFaces;
  }

  return {
    vertices: vertices.map((v) => ({
      x: v.x * scale,
      y: v.y * scale,
      z: v.z * scale,
    })),
    faces,
  };
};

export const surfaces = {
  sphere: {
    title: "Sphere",
    desc: [
      "A sphere is the set of all points in three-dimensional space at a fixed distance, known as the radius, from a central point. It is the most symmetrical 3D object and has constant positive Gaussian curvature.",
      'While simple UV-spheres concentrate resolution at the poles, this "Icosphere" is constructed through the recursive subdivision of an icosahedron. This results in a highly uniform distribution of vertices, providing true 3D structural symmetry.',
    ],
    formulas: [
      { label: "Cartesian Equation", eq: "x^2 + y^2 + z^2 = r^2" },
      { label: "Volume", eq: "V = \\frac{4}{3}\\pi r^3" },
      { label: "Surface Area", eq: "A = 4\\pi r^2" },
      { label: "Gaussian Curvature", eq: "K = \\frac{1}{r^2}" },
    ],
    generate: () => icosphere(2, 0.8),
  },
  torus: {
    title: "Torus",
    desc: [
      "A torus is a surface of revolution generated by revolving a circle in three-dimensional space about an axis coplanar with the circle. Topologically, it is the product of two circles.",
      "The torus is a fundamental object in topology and geometry. It characterizes the shape of donut-like objects and is used in models ranging from particle physics to cosmology.",
    ],
    formulas: [
      { label: "Implicit Equation", eq: "(\\sqrt{x^2+y^2} - R)^2 + z^2 = r^2" },
      { label: "Volume", eq: "V = 2\\pi^2 R r^2" },
      { label: "Surface Area", eq: "A = 4\\pi^2 R r" },
      { label: "Euler Characteristic", eq: "\\chi = 0" },
    ],
    generate: () =>
      parametric(32, 16, (u, v) => {
        const R = 0.6,
          r = 0.25;
        const s = 0.9;
        return {
          x: (R + r * Math.cos(v)) * Math.cos(u) * s,
          y: (R + r * Math.cos(v)) * Math.sin(u) * s,
          z: r * Math.sin(v) * s,
        };
      }),
  },
  mobius: {
    title: "Möbius Strip",
    desc: [
      'The Möbius strip is a surface with only one side and only one boundary component. It is the simplest non-orientable surface. If you trace a path along its length, you will return to your starting point but on the "opposite" side.',
      "It was discovered independently by August Ferdinand Möbius and Johann Benedict Listing in 1858. It is a cornerstone example in the field of topology, demonstrating how a simple twist can change a manifold's fundamental properties.",
    ],
    formulas: [
      { label: "Euler Characteristic", eq: "\\chi = 0" },
      { label: "Boundary", eq: "\\partial M \\cong S^1" },
      {
        label: "Parametric (Midline)",
        eq: "\\begin{cases} x = r\\cos\\theta \\\\ y = r\\sin\\theta \\\\ z = 0 \\end{cases}",
      },
    ],
    generate: () =>
      parametric(64, 10, (u, v) => {
        const t = v / (Math.PI * 2) - 0.5;
        const s = 0.6;
        return {
          x: (1 + t * Math.cos(u / 2)) * Math.cos(u) * s,
          y: (1 + t * Math.cos(u / 2)) * Math.sin(u) * s,
          z: t * Math.sin(u / 2) * s,
        };
      }),
  },
  klein: {
    title: "Klein Bottle",
    desc: [
      "The Klein bottle is a non-orientable closed surface with no boundary. It cannot be embedded in three-dimensional space without intersecting itself. It is a 2D manifold where a normal vector cannot be consistently defined.",
      'Mathematically, it can be thought of as two Möbius strips glued along their boundaries. In 4D space, the bottle can be closed without any self-intersection, making it a "closed" surface like the sphere, but with vastly different topological properties.',
    ],
    formulas: [
      { label: "Euler Characteristic", eq: "\\chi(M) = 0" },
      { label: "Genus", eq: "g = 2" },
      { label: "Chromatic Number", eq: "\\gamma(M) = 6" },
    ],
    generate: () =>
      parametric(
        40,
        40,
        (u, v) => {
          const cu = Math.cos(u),
            su = Math.sin(u),
            cv = Math.cos(v),
            sv = Math.sin(v);
          const x =
            (-2 / 15) *
            cu *
            (3 * cv -
              30 * su +
              90 * Math.pow(cu, 4) * su -
              60 * Math.pow(cu, 6) * su +
              5 * cu * cv * su);
          const y =
            (-1 / 15) *
            su *
            (3 * cv -
              3 * cu * cu * cv -
              48 * Math.pow(cu, 4) * cv +
              48 * Math.pow(cu, 6) * cv -
              60 * su +
              5 * cu * cv * su -
              5 * Math.pow(cu, 3) * cv * su -
              80 * Math.pow(cu, 5) * cv * su +
              80 * Math.pow(cu, 7) * cv * su);
          const z = (2 / 15) * (3 + 5 * cu * su) * sv;
          const s = 0.4;
          return { x: x * s, y: y * s, z: z * s };
        },
        [0, Math.PI],
        [0, Math.PI * 2],
      ),
  },
  boy: {
    title: "Boy's Surface",
    desc: [
      "Boy's surface is an immersion of the real projective plane in three-dimensional space. Discovered by Werner Boy in 1901, it solved the problem of finding a non-singular (no pinch points) immersion of the projective plane.",
      "Unlike the Roman surface, Boy's surface has no sharp edges or singular points, although it must intersect itself. It is a highly complex topological object that remains a subject of study in differential geometry.",
    ],
    formulas: [
      { label: "Topology", eq: "\\text{Immersion of } \\mathbb{RP}^2" },
      { label: "Euler Characteristic", eq: "\\chi = 1" },
    ],
    generate: () =>
      parametric(
        40,
        40,
        (u, v) => {
          const cu = Math.cos(u),
            su = Math.sin(u),
            cv = Math.cos(v);
          const d = 2 - Math.sqrt(2) * Math.sin(3 * u) * Math.sin(2 * v);
          const x =
            (Math.sqrt(2) * Math.cos(2 * u) * cv * cv + cu * Math.sin(2 * v)) /
            d;
          const y =
            (Math.sqrt(2) * Math.sin(2 * u) * cv * cv - su * Math.sin(2 * v)) /
            d;
          const z = (3 * cv * cv) / d - 1.25;
          const s = 0.5;
          return { x: x * s, y: y * s, z: z * s };
        },
        [0, Math.PI],
        [0, Math.PI],
      ),
  },
  hyper: {
    title: "Hyperboloid",
    desc: [
      "A hyperboloid of one sheet is a doubly ruled surface, meaning that through every point on the surface there pass two distinct straight lines that lie entirely on the surface.",
      "This structural property is widely used in architecture and engineering (e.g., cooling towers), as it allows the construction of curved structures using entirely straight beams. It is a quadric surface defined by an indefinite quadratic form.",
    ],
    formulas: [
      {
        label: "Cartesian Equation",
        eq: "\\frac{x^2}{a^2} + \\frac{y^2}{b^2} - \\frac{z^2}{c^2} = 1",
      },
      { label: "Gaussian Curvature", eq: "K < 0 \\text (Everywhere)" },
    ],
    generate: () =>
      parametric(
        30,
        30,
        (vIdx, u) => {
          const z = (vIdx / 30 - 0.5) * 2;
          const r = Math.sqrt(1 + z * z * 0.5);
          const s = 0.45;
          return { x: Math.cos(u) * r * s, y: Math.sin(u) * r * s, z: z * s };
        },
        [0, 30],
        [0, Math.PI * 2],
      ),
  },
  dini: {
    title: "Dini Surface",
    desc: [
      "Dini's surface is a surface with constant negative Gaussian curvature. It is constructed by twisting a pseudosphere, making it a rare example of a surface that is simultaneously a helicoid and a surface of constant curvature.",
      "Named after the Italian mathematician Ulisse Dini, it is a significant object in the study of differential geometry. Its complex, spiral-like appearance arises from the combination of linear vertical motion and circular rotation.",
    ],
    formulas: [
      { label: "Gaussian Curvature", eq: "K = -1" },
      {
        label: "Parametric Equations",
        eq: "\\begin{cases} x = a\\cos u\\sin v \\\\ y = a\\sin u\\sin v \\\\ z = a(\\cos v + \\ln(\\tan\\frac{v}{2})) + bu \\end{cases}",
      },
    ],
    generate: () =>
      parametric(
        60,
        20,
        (u, v) => {
          const x = Math.cos(u) * Math.sin(v);
          const y = Math.sin(u) * Math.sin(v);
          const z = Math.cos(v) + Math.log(Math.tan(v / 2)) + 0.15 * u;
          const s = 0.3;
          return { x: x * s, y: y * s, z: (z - 1.2) * s };
        },
        [0, Math.PI * 4],
        [0.01, 2.01],
      ),
  },
  enneper: {
    title: "Enneper Surface",
    desc: [
      "The Enneper surface is a self-intersecting minimal surface first described by Alfred Enneper in 1864. A minimal surface is one that locally minimizes its area, which is equivalent to having a mean curvature of zero.",
      "While the Enneper surface is mathematically elegant and defined by simple polynomial functions, its global self-intersection prevents it from being a physical model of a soap film beyond a small localized area.",
    ],
    formulas: [
      { label: "Mean Curvature", eq: "H = 0" },
      {
        label: "Parametric Equation",
        eq: "\\begin{cases} x = u - \\frac{u^3}{3} + uv^2 \\\\ y = v - \\frac{v^3}{3} + vu^2 \\\\ z = u^2 - v^2 \\end{cases}",
      },
    ],
    generate: () =>
      parametric(
        30,
        30,
        (u, v) => {
          const x = u - (u * u * u) / 3 + u * v * v;
          const y = v - (v * v * v) / 3 + v * u * u;
          const z = u * u - v * v;
          const s = 0.18;
          return { x: x * s, y: y * s, z: z * s };
        },
        [-2, 2],
        [-2, 2],
      ),
  },
  roman: {
    title: "Roman Surface",
    desc: [
      "The Roman surface (also known as the Steiner surface) is a self-intersecting immersion of the real projective plane in three-dimensional space. It has a high degree of symmetry, including six pinch points (Whitney singularities).",
      "Jacob Steiner discovered this surface while in Rome, hence its name. It is related to the Boy's surface but differs in having these specific singular points. It provides a visual way to understand the complex topology of the projective plane.",
    ],
    formulas: [
      { label: "Algebraic Equation", eq: "x^2y^2 + y^2z^2 + z^2x^2 + xyz = 0" },
      { label: "Genus", eq: "g = 1" },
    ],
    generate: () =>
      parametric(
        40,
        40,
        (u, v) => {
          const x = Math.sin(u) * Math.cos(u) * Math.sin(v) * Math.sin(v);
          const y = Math.sin(u) * Math.cos(v) * Math.sin(v);
          const z = Math.cos(u) * Math.cos(v) * Math.sin(v);
          const s = 1.8;
          return { x: x * s, y: y * s, z: z * s };
        },
        [0, Math.PI],
        [0, Math.PI],
      ),
  },
  kuen: {
    title: "Kuen Surface",
    desc: [
      "The Kuen surface is a famous example of a surface with constant negative Gaussian curvature. It features complex and aesthetically striking self-intersections.",
      "It belongs to the family of pseudospherical surfaces. Unlike the sphere, which has constant positive curvature, the Kuen surface illustrates the properties of hyperbolic geometry in a visual 3D context.",
    ],
    formulas: [
      { label: "Gaussian Curvature", eq: "K = -1" },
      { label: "Euler Characteristic", eq: "\\chi = -2" },
    ],
    generate: () =>
      parametric(
        50,
        30,
        (u, v) => {
          const d = 1 + u * u * Math.sin(v) * Math.sin(v);
          const x = (2 * (Math.cos(u) + u * Math.sin(u)) * Math.sin(v)) / d;
          const y = (2 * (Math.sin(u) - u * Math.cos(u)) * Math.sin(v)) / d;
          const z = Math.log(Math.tan(v / 2)) + (2 * Math.cos(v)) / d;
          const s = 0.25;
          return { x: x * s, y: y * s, z: z * s };
        },
        [-4.5, 4.5],
        [0.03, Math.PI * 0.98 + 0.03],
      ),
  },
  catenoid: {
    title: "Catenoid",
    desc: [
      "A catenoid is the unique minimal surface of revolution other than the plane. It is generated by rotating a catenary curve (the shape of a hanging chain) about an axis.",
      "First discovered by Leonhard Euler in 1744, it can be physically modeled by a soap film stretching between two circular rings. It is topologically equivalent to an annulus and has a mean curvature of zero at every point.",
    ],
    formulas: [
      {
        label: "Equation (Rotation)",
        eq: "\\sqrt{x^2 + y^2} = c \\cosh(\\frac{z}{c})",
      },
      { label: "Mean Curvature", eq: "H = 0" },
      {
        label: "Gaussian Curvature",
        eq: "K = -\\text{sech}^4(\\frac{z}{c})/c^2",
      },
    ],
    generate: () =>
      parametric(
        40,
        40,
        (u, v) => {
          const c = 0.5;
          const x = c * Math.cosh(v / c) * Math.cos(u);
          const y = c * Math.cosh(v / c) * Math.sin(u);
          const z = v;
          const s = 0.55;
          return { x: x * s, y: y * s, z: z * s };
        },
        [0, Math.PI * 2],
        [-1.2, 1.2],
      ),
  },
};
