/**
 * js/shapes/torus.js
 * 構造の説明: トーラス
 */

import { parametric } from "../utils.js";

export const torus = {
  title: "Torus",
  desc: [
    "A torus is a surface of revolution generated by revolving a circle in three-dimensional space about an axis coplanar with the circle. Topologically, it is the product of two circles.",
    "The torus is a fundamental object in topology and geometry. It characterizes doughnut-shaped forms and is used in models ranging from particle physics to cosmology.",
  ],
  formulas: [
    {
      label: "Implicit Representation",
      eq: "(\\sqrt{x^2+y^2} - R)^2 + z^2 = r^2",
    },
    { label: "Volume", eq: "V = 2\\pi^2 R r^2" },
    { label: "Surface Area", eq: "A = 4\\pi^2 R r" },
    { label: "Euler Characteristic", eq: "\\chi = 0" },
  ],
  generate: () =>
    parametric(32, 16, (u, v) => {
      const R = 0.6,
        r = 0.25;
      const s = 0.9;
      return {
        x: (R + r * Math.cos(v)) * Math.cos(u) * s,
        y: (R + r * Math.cos(v)) * Math.sin(u) * s,
        z: r * Math.sin(v) * s,
      };
    }),
};
