import type { Discipline, ShapeDefinition } from "../types";
import { tetrahedron } from "./tetrahedron";
import { cube } from "./cube";
import { octahedron } from "./octahedron";
import { dodecahedron } from "./dodecahedron";
import { icosahedron } from "./icosahedron";
import { bucky } from "./bucky";
import { sphere } from "./sphere";
import { torus } from "./torus";
import { mobius } from "./mobius";
import { klein } from "./klein";
import { boy } from "./boy";
import { hyper } from "./hyper";
import { dini } from "./dini";
import { enneper } from "./enneper";
import { roman } from "./roman";
import { kuen } from "./kuen";
import { catenoid } from "./catenoid";
import { dna } from "./dna";
import { knot } from "./knot";
import { superShape } from "./super";
import { calabi } from "./calabi";
import { lorenz } from "./lorenz";
import { tesseract } from "./tesseract";
import { orrery } from "./orrery";
import { sierpinski } from "./sierpinski";
import { honeycomb } from "./honeycomb";
import { chladni } from "./chladni";
import { interference } from "./interference";
import { schwarzschild } from "./schwarzschild";
import { diamond } from "./diamond";
import { nanotube } from "./nanotube";
import { radiolarian } from "./radiolarian";
import { capsid } from "./capsid";
import { breather } from "./breather";
import { graphite } from "./graphite";
import { phyllotaxis } from "./phyllotaxis";
import { diatom } from "./diatom";
import { binaryTree } from "./tree";

export const disciplines: Discipline[] = [
  {
    name: "Mathematics",
    id: "math",
    desc: "The study of numbers, shapes, and patterns that form the foundation of logic.",
    groups: [
      {
        name: "Platonic Solids",
        desc: "Regular, convex polyhedra with identical faces made of regular polygons.",
        shapes: [
          "tetrahedron",
          "cube",
          "octahedron",
          "dodecahedron",
          "icosahedron",
        ],
      },
      {
        name: "Geometric Surfaces",
        desc: "Fundamental shapes and smooth surfaces found in classical geometry.",
        shapes: [
          "sphere",
          "torus",
          "hyper",
          "catenoid",
          "enneper",
          "dini",
          "kuen",
          "breather",
        ],
      },
      {
        name: "Fractals and Tilings",
        desc: "Complex patterns generated by simple recursive rules or efficient space-filling.",
        shapes: ["sierpinski", "honeycomb"],
      },
      {
        name: "Topology and Higher Dimensions",
        desc: "Shapes that explore connectivity and dimensions beyond our everyday experience.",
        shapes: ["mobius", "klein", "boy", "roman", "knot", "tesseract"],
      },
    ],
  },
  {
    name: "Physics",
    id: "physics",
    desc: "The science of matter, energy, and the fundamental forces of the universe.",
    groups: [
      {
        name: "Waves and Vibrations",
        desc: "Visualizations of wave interference and resonant frequencies.",
        shapes: ["chladni", "interference"],
      },
      {
        name: "Celestial Mechanics and Astrophysics",
        desc: "The study of orbital motions and the nature of celestial bodies.",
        shapes: ["orrery", "schwarzschild"],
      },
      {
        name: "Chaos and Dynamical Systems",
        desc: "Complex behaviors emerging from simple deterministic laws.",
        shapes: ["lorenz"],
      },
      {
        name: "Quantum Mechanics",
        desc: "Mathematical models of atomic structures and higher-dimensional manifolds.",
        shapes: ["calabi"],
      },
    ],
  },
  {
    name: "Chemistry",
    id: "chemistry",
    desc: "The study of substances, their properties, and how they interact and change.",
    groups: [
      {
        name: "Crystal Lattices",
        desc: "Ordered arrangements of atoms and ions in solid materials.",
        shapes: ["diamond", "graphite"],
      },
      {
        name: "Molecular Nanostructures",
        desc: "The geometry of fullerenes and carbon-based nanomaterials.",
        shapes: ["bucky", "nanotube"],
      },
    ],
  },
  {
    name: "Biology",
    id: "biology",
    desc: "The study of living organisms and the vital processes that sustain life.",
    groups: [
      {
        name: "Biological Morphogenesis",
        desc: "Geometric patterns found in plant growth and organic forms.",
        shapes: ["super", "phyllotaxis"],
      },
      {
        name: "Microscopic Structures",
        desc: "The intricate skeletons and shells of microscopic organisms and viruses.",
        shapes: ["dna", "radiolarian", "capsid", "diatom"],
      },
    ],
  },
  {
    name: "Engineering & CS",
    id: "engineering",
    desc: "Application of science and math to solve problems and build structures.",
    groups: [
      {
        name: "Recursive Algorithms",
        desc: "Visualization of data structures and recursive state spaces.",
        shapes: ["tree"],
      },
    ],
  },
];

export const shapes: Record<string, ShapeDefinition> = {
  tetrahedron,
  cube,
  octahedron,
  dodecahedron,
  icosahedron,
  bucky,
  sphere,
  torus,
  mobius,
  klein,
  boy,
  hyper,
  dini,
  enneper,
  roman,
  kuen,
  catenoid,
  dna,
  knot,
  super: superShape,
  calabi,
  lorenz,
  tesseract,
  orrery,
  sierpinski,
  honeycomb,
  chladni,
  interference,
  schwarzschild,
  diamond,
  nanotube,
  radiolarian,
  capsid,
  breather,
  graphite,
  phyllotaxis,
  diatom,
  tree: binaryTree,
};

export const orderedIds = disciplines.flatMap(d => d.groups.flatMap(g => g.shapes));
