/**
 * js/shapes/sphere.js
 * 構造の説明: 球面
 */

import type { ShapeDefinition, Vector3, Geometry } from "../types";
import {  subdivide, vec  } from "../utils/math";
import { ICO_VERTICES, ICO_FACES } from "./icosahedron.js";

/**
 * 正二十面体を細分化して、アイコスフィア（正二十面体近似球）を生成します。
 * UV球よりも頂点分布が均一になります。
 *
 * @param {number} iterations - 細分化の回数.
 * @param {number} scale - 球の半径.
 * @returns {Geometry} 生成された {vertices, faces}。
 */
const icosphere = (iterations = 2, scale = 0.8): Geometry => {
  let geo: any = { vertices: ICO_VERTICES, faces: ICO_FACES };

  for (let i = 0; i < iterations; i++) {
    geo = subdivide(geo, true);
  }

  return {
    vertices: geo.vertices.map((v: Vector3) => vec.mul(v, scale)),
    faces: geo.faces,
  };
};

export const sphere: ShapeDefinition = {
  id: "sphere",
  title: "Sphere",
  desc: [
    "A sphere is the locus of points in 3D Euclidean space equidistant from a fixed center. It is a perfectly symmetrical manifold (S^2) with a constant positive Gaussian curvature of 1/r^2. This specific implementation uses an 'icosphere' topology, generated by subdividing a regular icosahedron to ensure uniform vertex density and avoid polar singularities found in standard UV grids.",
    "Spherical geometry has been studied since the time of the ancient Greeks, with Euclid and Archimedes defining its properties. It is the fundamental shape of celestial bodies under gravity and serves as the basis for global coordinate systems and non-Euclidean elliptic geometry.",
  ],
  formulas: [
    { label: "Implicit Equation", eq: "x^2 + y^2 + z^2 = 1" },
    { label: "Gaussian Curvature", eq: "K = 1" },
  ],
  generate: (_counter: number): Geometry => icosphere(2, 0.8),
};
