/**
 * js/shapes/hyper.js
 * 構造の説明: 一葉双曲面
 */

import type { ShapeDefinition, Vector3, Geometry } from "../types";
import {  parametric  } from "../utils/math";

export const hyper: ShapeDefinition = {
  id: "hyper",
  title: "Hyperboloid of One Sheet",
  hideVertices: true,
  desc: [
    "A hyperboloid of one sheet is a quadric surface that is notably a doubly ruled surface. This unique geometric property means that through every point on the surface, there are two distinct straight lines that lie entirely within the surface. This makes it exceptionally strong and efficient for structural engineering and architectural designs.",
    "Commonly seen in the design of cooling towers and hyperbolic structures, its geometry provides high structural integrity with minimal material. It is generated by rotating a hyperbola about its conjugate axis or by a linear transformation of a cylinder, representing a negative Gaussian curvature surface with rotational symmetry.",
  ],
  formulas: [
    { label: "Implicit Equation", eq: "x^2 + y^2 - z^2 = 1" },
    { label: "Gaussian Curvature", eq: "K = -\\frac{1}{(x^2 + y^2 + z^2)^2}" },
  ],
  generate: (_counter: number): Geometry =>
    parametric(
      30,
      30,
      (u: number, v: number): Vector3 => {
        const z = (u / 30 - 0.5) * 2;
        const r = Math.sqrt(1 + z * z * 0.5);
        const s = 0.45;
        return { x: Math.cos(v) * r * s, y: Math.sin(v) * r * s, z: z * s };
      },
      [0, 30],
      [0, Math.PI * 2],
    ),
};
